export {default as IndexController} from './products'
export {default as ProductPreviewController} from './products/view'
export {default as CartController} from './my-cart'
export {default as SearchController} from './search'
export {default as FavoriteController} from './favorite'
export {default as SuccessPaymentController} from './success-payment'
export {default as ErrorPaymentController} from './error-payment'